### ISSUE TITLE
How to run program

### ISSUE THREAD

**Issue by Karimi-81** [ifremer-bioinformatics/pallor#1]
Hi There,
I wonder if you could provide more details on running the program. I cannot find any params.config in the  conf directory. It is not clear how to adjust parameter file. I would be appreciated if you could provide an example here.
Thanks

**Comment by alexcorm** [comment]
Hi Karimi,
I've just pushed the latest version of PALLOR on Master Branch. I've added documentation and few examples.
You can run the program using arguments (--min_species for example) or you can edit custom.config into conf/ to set each parameters.
